"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# All env vars in this file go through django-environ: one idiom instead of
# ad-hoc os.environ.get(...)/comma-splitting, and — the property this project
# actually relies on below — env.str(name) with no default raises Django's
# own ImproperlyConfigured when the var is missing, instead of silently
# falling back to something insecure.
env = environ.Env(DJANGO_DEBUG=(bool, False))
# Local development: pick up .env from the project root (in .gitignore).
# overwrite=False (default) — in prod (dokku injects env, no .env present)
# this is a no-op; missing entirely is also fine (read_env tolerates it).
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False — insecure settings must be opted into, never assumed.
# Local dev sets DJANGO_DEBUG=True in .env (see .env.example).
DEBUG = env('DJANGO_DEBUG')

# SECURITY WARNING: keep the secret key used in production secret!
# The insecure literal is only ever a default in DEBUG mode; in production a
# missing DJANGO_SECRET_KEY must crash at boot, not silently ship a key
# that's public in this file's git history.
_INSECURE_DEV_KEY = 'django-insecure-)9u#_m)-fi$l#tzetjy2d971n#q6$$)l$-2*y8h!qaw*l1vn0+'
SECRET_KEY = (
    env.str('DJANGO_SECRET_KEY', default=_INSECURE_DEV_KEY) if DEBUG
    else env.str('DJANGO_SECRET_KEY')
)

# Same reasoning as SECRET_KEY above: with DEBUG=False an empty ALLOWED_HOSTS
# doesn't just 400 every request, it also silently empties
# CSRF_TRUSTED_ORIGINS below — so require it rather than defaulting to [].
ALLOWED_HOSTS = (
    env.list('DJANGO_ALLOWED_HOSTS', default=[]) if DEBUG
    else env.list('DJANGO_ALLOWED_HOSTS')
)

# Prod goes browser -> Cloudflare edge (TLS terminates HERE, not any closer
# to the app) -> Cloudflare Tunnel -> dokku nginx -> gunicorn, with the last
# two hops both plain HTTP. Without this Django considers every request
# insecure (request.is_secure() == False) and the CSRF Origin-header check
# (the browser sends "https://...") doesn't match the computed "http://..."
# scheme -> 403 on every POST, regardless of whether the CSRF token itself is
# correct. This alone isn't sufficient, though: dokku's nginx must also be
# told to trust Cloudflare's own X-Forwarded-Proto instead of stamping its
# own connection scheme onto it (always "http" here) — a per-app dokku nginx
# setting, not something this file controls. See CLAUDE.md ("CSRF behind a
# reverse proxy") for the exact command and why this was easy to miss.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS]

if not DEBUG:
    # Cookies only ever travel over the Cloudflare Tunnel's HTTPS front door.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Deliberately NOT SECURE_SSL_REDIRECT: dokku nginx already terminates
    # TLS and redirects http->https in front of gunicorn (see the
    # SECURE_PROXY_SSL_HEADER comment above) — enabling Django's own redirect
    # on top would risk a loop, since request.is_secure() here reflects the
    # trusted proxy header, not the actual connection to this process.
    # `manage.py check --deploy`'s W008 for this is expected and silenced
    # below, not an oversight.
    SILENCED_SYSTEM_CHECKS = ['security.W008']

# A legitimate request body (a move-log POST) is a couple KB; this caps
# parsing cost for an oversized payload well before gameplay/schemas.py even
# sees it (see FinishRequest/ShuffleRequest.moves, which have no max_length
# of their own).
DATA_UPLOAD_MAX_MEMORY_SIZE = 1_000_000

# Pexels API key for the game's background photos (docs/superpowers/specs/... background).
# Empty string = background disabled, client gets {"url": null} and keeps the default color.
PEXELS_API_KEY = env.str('PEXELS_API_KEY', default='')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gameplay',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Must sit between SessionMiddleware and CommonMiddleware: resolves the
    # active language from the language cookie / Accept-Language and activates
    # it for this request (translation.get_language() from here on).
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'gameplay.middleware.PlayerIdentityMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db_url('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
}
# django-environ's db_url() only promotes conn_max_age when it's a query
# parameter INSIDE the URL (?conn_max_age=600) — there's no kwarg for it like
# the old dj_database_url.config(conn_max_age=...) had. Set it explicitly so
# connection reuse doesn't silently vanish the day DATABASE_URL is set
# without that query string.
DATABASES['default']['CONN_MAX_AGE'] = 600


# Cache
# Optional — unset REDIS_URL keeps Django's default LocMemCache, a
# per-process cache. That's fine for a single worker, but under gunicorn with
# WEB_CONCURRENCY > 1 it means gameplay/ratelimit.py's per-IP quotas are
# effectively quota × worker count (each worker counts independently), and
# config/api.py's Pexels photo pool is fetched once per worker instead of
# once per TTL. Setting REDIS_URL makes both exact across the whole cluster.
REDIS_URL = env.str('REDIS_URL', default='')
if REDIS_URL:
    CACHES = {
        'default': {
            # django-redis, not Django's built-in
            # django.core.cache.backends.redis.RedisCache: the built-in one
            # raises redis.exceptions.RedisError from every cache op when the
            # server is unreachable (verified — even a plain socket timeout
            # still raises), which would 500 every rate-limited endpoint and
            # /api/background during a Redis blip. IGNORE_EXCEPTIONS below
            # makes an outage degrade to a cache miss instead — rate limits
            # fail open, the Pexels pool re-fetches — which is the right
            # trade for a solitaire game. Not env.cache_url('REDIS_URL'):
            # that helper's redis:// scheme resolves to this same backend
            # only if django-redis happens to be installed, and silently to
            # the raising built-in one otherwise (environ/compat.py:
            # choose_rediscache_driver) — removing the dependency would
            # quietly swap in the backend that 500s and feed it OPTIONS keys
            # it doesn't understand, so the backend is named explicitly here.
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            # Namespaces this app on a Redis instance that may be shared with
            # other home-LAN services; which logical database is selected by
            # the path in REDIS_URL (e.g. .../1) — see CLAUDE.md.
            'KEY_PREFIX': 'mahjong',
            'OPTIONS': {
                'IGNORE_EXCEPTIONS': True,
                # IGNORE_EXCEPTIONS bounds the *outcome* of an outage, not
                # the *wait* — against a host that drops packets instead of
                # refusing the connection, an unbounded connect would hang a
                # gunicorn worker. 1s is already generous for a LAN hop.
                'SOCKET_CONNECT_TIMEOUT': 1,
                'SOCKET_TIMEOUT': 1,
            },
        },
    }
    # Without this, IGNORE_EXCEPTIONS silently swallows every failure — an
    # outage would look like "quotas mysteriously stopped applying" with
    # nothing in the log.
    DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Default for a fresh visitor with no cookie and no matching Accept-Language.
LANGUAGE_CODE = 'uk'

LANGUAGES = [
    ('uk', _('Ukrainian')),
    ('en', _('English')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Stock whitenoise storage: compression + manifest hashing (hash in the
        # filename = cache busting). Rewriting ES imports is no longer needed —
        # all JS is bundled by esbuild into one bundle.js (Dockerfile jsbuild stage).
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
