# Generated by Django 6.0.7 on 2026-07-17 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=16)),
                ('layout', models.JSONField()),
                ('seed', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='active', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('won', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='gameplay_ga_created_db986a_idx')],
            },
        ),
    ]
