# Generated by Django 6.0.7 on 2026-07-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_gamesession_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='shuffles',
            field=models.JSONField(default=list),
        ),
    ]
