# Generated by Django 6.0.7 on 2026-07-28 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_gamesession_shuffles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='daily_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='hints',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='score_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='undos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['daily_date', 'score_ms'], name='gameplay_ga_daily_d_9ffb10_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(condition=models.Q(('daily_date__isnull', False)), fields=('user', 'daily_date'), name='one_daily_attempt_per_user_per_day'),
        ),
    ]
