# Generated by Django 6.0.7 on 2026-07-28 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_gamesession_daily_date_gamesession_hints_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gamesession',
            name='one_daily_attempt_per_user_per_day',
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(condition=models.Q(('daily_date__isnull', False), ('won', True)), fields=('user', 'daily_date'), name='one_daily_win_per_user_per_day'),
        ),
    ]
