# Generated by Django 6.0.8 on 2026-08-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_remove_gamesession_one_daily_attempt_per_user_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
